#!/bin/bash

echo "=================================================="
echo "🔍 GitHub Actions 部署失败诊断"
echo "=================================================="
echo ""

# 第1步：检查 SSH 连接
echo "第1步：测试 SSH 连接到服务器..."
echo ""
echo "正在连接 root@119.29.95.149 ..."
echo ""

if ssh -o ConnectTimeout=5 -o StrictHostKeyChecking=no root@119.29.95.149 "echo '✅ SSH 连接成功'" 2>/dev/null; then
    echo "✅ SSH 连接正常"
    echo ""
    echo "这意味着："
    echo "  - 服务器在线"
    echo "  - SSH 密钥正确"
    echo "  - 本地可以连接"
    echo ""
    echo "❌ 问题在 GitHub Actions！"
    echo ""
    echo "最可能的原因："
    echo "  GitHub Secret SERVER_SSH_KEY 未配置或配置错误"
    echo ""
    echo "=================================================="
    echo "🔧 立即修复步骤："
    echo "=================================================="
    echo ""
    echo "1. 访问："
    echo "   https://github.com/djx-ux/-CICD/settings/secrets/actions"
    echo ""
    echo "2. 检查是否有 SERVER_SSH_KEY"
    echo "   - 如果没有，点击 'New repository secret'"
    echo "   - Name: SERVER_SSH_KEY"
    echo "   - Secret: [粘贴完整的 SSH 私钥]"
    echo ""
    echo "3. 你的 SSH 私钥内容（复制下面全部）："
    echo "   -----BEGIN OPENSSH PRIVATE KEY-----"
    echo "   b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW"
    echo "   QyNTUxOQAAACD84jYWEqraE9+rb6uToRbGMHnxN9fgbXhdSLX79bpPHwAAAKAycg75MnIO"
    echo "   +QAAAAtzc2gtZWQyNTUxOQAAACD84jYWEqraE9+rb6uToRbGMHnxN9fgbXhdSLX79bpPHw"
    echo "   AAAEA6S7x5izDScoc1KdDCf/1jNa9lLCf0dEdoxMF74g33bPziNhYSqtoT36tvq5OhFsYw"
    echo "   efE31+BteF1Itfv1uk8fAAAAFnlvdXJfZW1haWxAZXhhbXBsZS5jb20BAgMEBQYH"
    echo "   -----END OPENSSH PRIVATE KEY-----"
    echo ""
    echo "4. 保存后，重新运行 GitHub Actions"
    echo "   访问：https://github.com/djx-ux/-CICD/actions"
    echo "   点击最新的失败运行 → Re-run all jobs"
    echo ""
else
    echo "❌ SSH 连接失败"
    echo ""
    echo "可能的原因："
    echo "  1. 服务器不在线"
    echo "  2. SSH 服务未启动"
    echo "  3. 防火墙阻止"
    echo "  4. IP 地址错误"
    echo ""
    echo "请检查："
    echo "  - 服务器是否开机"
    echo "  - IP 地址是否正确：119.29.95.149"
    echo "  - 防火墙是否允许 22 端口"
    echo ""
fi

# 第2步：检查服务器 Docker
echo ""
echo "=================================================="
echo "第2步：检查服务器 Docker 状态"
echo "=================================================="
echo ""

if ssh -o ConnectTimeout=5 root@119.29.95.149 "docker --version" 2>/dev/null; then
    echo "✅ Docker 已安装"
    
    echo ""
    echo "当前运行的容器："
    ssh root@119.29.95.149 "docker ps" 2>/dev/null || echo "❌ 无法获取容器列表"
else
    echo "❌ Docker 未安装或无法访问"
    echo ""
    echo "请在服务器上安装 Docker："
    echo "  ssh root@119.29.95.149"
    echo "  curl -fsSL https://get.docker.com | sh"
fi

echo ""
echo "=================================================="
echo "📊 诊断完成"
echo "=================================================="
echo ""

